#ifndef COMMON_PA3_ERROR_H
#define COMMON_PA3_ERROR_H

typedef enum {
  PARSING_SUCCESS,
  PARSING_NO_REQUEST,
  PARSING_NO_ACTION,
  PARSING_NO_DATA,
  PARSING_NOT_LOGGED_IN,
  PARSING_ALREADY_LOGGED_IN,
  PARSING_INVALID_ACTION,
} ParsingError;

typedef enum {
  LOGIN_ERROR_SUCCESS,
  LOGIN_ERROR_ACTIVE_USER,
  LOGIN_ERROR_ACTIVE_CLIENT,
  LOGIN_ERROR_INCORRECT_PASSWORD,
  LOGIN_ERROR_NO_PASSWORD,
  LOGIN_ERROR_NO_USERNAME_AND_PASSWORD,
} LoginErrorCode;

typedef enum {
  BOOK_ERROR_SUCCESS,
  BOOK_ERROR_USER_NOT_LOGGED_IN,
  BOOK_ERROR_SEAT_UNAVAILABLE,
  BOOK_ERROR_SEAT_OUT_OF_RANGE,
  BOOK_ERROR_NO_DATA
} BookErrorCode;

typedef enum {
  CANCEL_BOOKING_ERROR_SUCCESS,
  CANCEL_BOOKING_ERROR_USER_NOT_LOGGED_IN,
  CANCEL_BOOKING_ERROR_SEAT_NOT_BOOKED_BY_USER,
  CANCEL_BOOKING_ERROR_SEAT_OUT_OF_RANGE,
  CANCEL_BOOKING_ERROR_NO_DATA,
} CancelBookingErrorCode;

typedef enum {
  CONFIRM_BOOKING_ERROR_SUCCESS,
  CONFIRM_BOOKING_ERROR_USER_NOT_LOGGED_IN,
  CONFIRM_BOOKING_ERROR_INVALID_DATA,
  CONFIRM_BOOKING_ERROR_NO_DATA
} ConfirmBookingErrorCode;

typedef enum {
  LOGOUT_ERROR_SUCCESS,
  LOGOUT_ERROR_USER_NOT_FOUND,
  LOGOUT_ERROR_USER_NOT_LOGGED_IN,
} LogoutErrorCode;

typedef enum {
  QUERY_ERROR_SUCCESS,
  QUERY_ERROR_SEAT_OUT_OF_RANGE,
  QUERY_ERROR_NO_DATA
} QueryErrorCode;

#endif
